### PR TITLE
Semantic segmentation plugin

### PR DESCRIPTION
**Pull request by joemarshall**
Added support for multiple models of semantic segmentation including
deeplabv3plus which should work better than the existing deeplabv3

Mainly I was just trying here to see how hard it was to bring a new model in, but this does work a little bit better than the plain deeplabv3 plugin.

### CODE REVIEW

**Comment by valgur** [comment]
Hi! This is excellent and exactly the kind of flexibility with model choices I had in mind when I changed the GIMP-ML architecture to be based on the Torch Hub format.

I will gladly merge this PR, but I'm not too eager about the implication of creating a separate fork of GIMP-ML just yet. I would prefer these changes to be part of the main repo, but this is up to @kritiksoman. I guess I will have to fork GIMP-ML for good at some point if he remains unresponsive.

The code for the plugin and the added `hubconf.py` look good. There are some minor issues and cosmetic adjustments I would prefer to be included before this PR can be merged, though:
- The plugin script must have the executable bit set for GIMP to recognize it as a plugin. I assume you are developing on Windows and this just worked semi-accidentally? Anyway, please apply `git update-index --chmod=+x plugins/semanticsegmentation.py` to make sure it works on Unix platforms also.
-  Please set `progress=True` for `load_state_dict_from_url()` in the `hubconf.py` file. This is required for having the model download progress displayed in GIMP. Better yet if you make this a parameter of the model callables in `hubconf.py`.
- I would name the plugin file `semantic_segmentation.py` and the model file `DeepLabv3.py`. You can remove the previous DeepLabv3 plugin and model.
- Please follow [PEP 8](https://www.python.org/dev/peps/pep-0008/) for the code style. I say this mostly regarding the variable name style, where you should prefer `snake_case` instead of `camelCase` for Python code unless there is a good reason not to.
- For consistent formatting applying an auto-formatter would be nice. Good options are PyCharm's built-in auto-formatting and [black](https://github.com/psf/black).

**Comment by joemarshall** [comment]
Oops, I've been programming in 3 different languages recently so I'm not hot on case styles and the like! Will fix these things in a couple of days once I've got time after I've finished marking student work.

Next thoughts for things I want in gimp is this deblur: it's surprisingly simple and the results look great. I'll try to add that at some point soon.

https://github.com/csdwren/SelfDeblur/blob/master/selfdeblur_nonblind.py

**Comment by valgur** [comment]
> Next thoughts for things I want in gimp is this deblur: it's surprisingly simple and the results look great. I'll try to add that at some point soon.

Looking forward to your PR. :+1:
You can apply the same logic I used for adding MiDaS to the monocular depth plugin to provide a choice between the existing DeblurGANv2 model and SelfDeblur: https://github.com/valgur/GIMP-ML/blob/master/plugins/monocular_depth.py

**Comment by joemarshall** [comment]
Think I've fixed the code style etc. on this now, and added the progress callbacks

**Comment by joemarshall** [comment]
Code and permissions fixed now, think it is good to merge, but I can't test on unix here?

**Comment by valgur** [comment]
Looks good to me now. Thank you!

**Pull request merged**
